### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by ColonelGerdauf** [Darkhax-Minecraft/Better-Burning#14]
This mod is in need of 1.18.2 support. This might effectively be a backport when approached from 1.19.4.

I think this might be easier when approached from 1.16.5, given that the 1.19.4 version is quite new, and 1.18.x is still a straightforward release model unlike 1.19.x.

Many Forge modpacks and modlists stick to 1.18 at the highest, due to the fact that many mods appear reluctant to update to 1.19, plus there is so much confusion over which mods are on which sub-version.

**Comment by Darkhax** [comment]
Sorry for not replying to this sooner. With Mojang's new release schedule and 4 different modloaders to support I don't have much time to spend on backports. In this case it was not a simple backport because of all the data driven changes and API rewrites in Forge that took place in 1.19. 

I don't really agree with your opinions on 1.18 vs 1.19+, but that doesn't matter. I hope you, or at least other players can still benefit from this backport. You can find the file [here](https://www.curseforge.com/minecraft/mc-mods/better-burning/files/5166111) once CurseForge has had time to process and review the file.
